apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-app-config
data:
  app_port: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: pingpong-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: pingpong-app-config
                  key: app_port
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-app-ingress
spec:
  rules:
    - host: api.pinpong.web
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingpong-app-service
                port:
                  number: 80